### ISSUE TITLE
Incompatible with Hydrogen?

### ISSUE THREAD

**Issue by VileSmith** [LucilleTea/cadmium-fabric#2]
My minecraft crashes when I try to use Cadmium with Hydrogen (The two most recent)

**Comment by silversquirl** [comment]
Could you upload a crash report from `.minecraft/crash-reports` and/or latest.log `.minecraft/logs`?

**Comment by ferreiraevil** [comment]
[2021-02-12-5.log.gz](https://github.com/LucilleTea/cadmium-fabric/files/5973810/2021-02-12-5.log.gz)

**Comment by ferreiraevil** [comment]
[16:54:57] [main/INFO]: Loading for game Minecraft 1.16.4
[16:54:59] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: hydrogen requires {minecraft @ [1.16.5]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-loader-0.11.1.jar:?]
	... 5 more

**Comment by VileSmith** [comment]
[16:57:04] [main/INFO]: Loading for game Minecraft 1.16.4
[16:57:05] [main/INFO]: [FabricLoader] Loading 57 mods: fabric-renderer-api-v1@0.4.0+cbe9176f3a, fabric-keybindings-v0@0.2.0+6a2618f53a, fabricloader@0.11.1, hydrogen@0.1.2-SNAPSHOT, fabric-structure-api-v1@1.1.3+cbe9176f3a, fabric-containers-v0@0.1.9+a03e98793a, lithium@0.6.3, fabric-dimensions-v1@2.0.1+9a6c75813a, fabric-object-builder-api-v1@1.9.2+6a2618f53a, java@8, umollu_ash@1.1.13, cotton-client-commands@1.0.1+1.16-rc1, fabric-game-rule-api-v1@1.0.5+cbe9176f3a, fabric-api-base@0.2.0+ab87788d3a, fabric-rendering-data-attachment-v1@0.1.4+6a2618f53a, fabric-textures-v0@1.0.5+6a2618f53a, fabric-rendering-fluids-v1@0.1.12+6a2618f53a, fabric-blockrenderlayer-v1@1.1.4+6a2618f53a, fabric-lifecycle-events-v1@1.2.0+ffb68a873a, sodium@0.1.0, fabric-renderer-registries-v1@2.2.0+6a2618f53a, fabric-loot-tables-v1@1.0.1+6a2618f53a, fabric@0.29.3+1.16, fabric-particles-v1@0.2.3+cbe9176f3a, cadmium@0.1.0-lucilletea.1, fabric-networking-v0@0.3.1+2a4333d33a, no_fog@1.0.2-beta.1+1.16.2, fabric-networking-blockentity-v0@0.2.7+a03e98793a, minecraft@1.16.4, fabric-screen-handler-api-v1@1.1.0+6a2618f53a, fabric-command-api-v1@1.0.9+6a2618f53a, cloth-basic-math@0.5.1, phosphor@0.7.1+build.11, fabric-tool-attribute-api-v1@1.2.5+6a2618f53a, fabric-renderer-indigo@0.4.3+6a2618f53a, fabric-events-interaction-v0@0.4.1+6a2618f53a, fabric-crash-report-info-v1@0.1.2+b7f9825d3a, fabric-item-api-v1@1.2.0+6a2618f53a, fabric-entity-events-v1@1.0.2+8004b36d3a, fabric-rendering-v0@1.1.1+6a2618f53a, cullleaves@2.0.0, fabric-key-binding-api-v1@1.0.1+730711c63a, fabric-rendering-v1@1.5.0+c26373133a, cloth-config2@4.8.3, fabric-resource-loader-v0@0.4.1+0d4d7e343a, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.0+e77439c73a, fabric-tag-extensions-v0@1.1.0+e77439c73a, fabric-biome-api-v1@3.1.0+2e23b97c3a, fabric-registry-sync-v0@0.7.3+be155ae23a, fabric-commands-v0@0.2.1+cbe9176f3a, fabric-mining-levels-v0@0.1.2+6a2618f53a, fabric-networking-api-v1@1.0.0+4358fbc63a, fabric-events-lifecycle-v0@0.2.0+6a2618f53a, fabric-item-groups-v0@0.2.2+cbe9176f3a, fabric-models-v0@0.2.0+cbe9176f3a, fabric-object-builders-v0@0.7.1+6a2618f53a
[16:57:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/igorf/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[16:57:05] [main/INFO]: Loaded configuration file for Sodium (38 options available, 0 user overrides)
[16:57:05] [main/INFO]: Sodium has been successfully discovered and initialized -- your game is now faster!
[16:57:06] [main/INFO]: Loaded configuration file for Lithium: 76 options available, 0 override(s) found
[16:57:06] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[16:57:06] [main/WARN]: Trying to reflect-hack into the class-loader so we can define our own classes in an unrestricted loader...
[16:57:06] [main/WARN]: ** The JVM might warn you with something nasty! **
[16:57:06] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/C:/Users/igorf/AppData/Roaming/.minecraft/mods/hydrogen-fabric-mc1.16.4-0.1.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[16:57:06] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/C:/Users/igorf/AppData/Roaming/.minecraft/mods/hydrogen-fabric-mc1.16.4-0.1.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[16:57:06] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/C:/Users/igorf/AppData/Roaming/.minecraft/mods/hydrogen-fabric-mc1.16.4-0.1.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySet.class)
[16:57:06] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/C:/Users/igorf/AppData/Roaming/.minecraft/mods/hydrogen-fabric-mc1.16.4-0.1.2-SNAPSHOT.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[16:57:06] [main/INFO]: Using classpath injector: me.jellysquid.mods.cadmium.inject.KnotClasspathInjector@21d5c1a0
[16:57:06] [main/INFO]: Mounted library '/META-INF/jar-replacements/DataFixerUpper-4.0.0-SNAPSHOT.jar' with hash 8c1acc46318b0139660299b7f20358d70321089f41391536280fcb2ace75a913
[16:57:06] [main/INFO]: Added jimfs://a01adcff-fc94-481c-9e0b-4d45bdbab65e/C:/work/8c1acc46318b0139660299b7f20358d70321089f41391536280fcb2ace75a913.jar to classpath injection list
[16:57:06] [main/INFO]: Successfully injected libraries into classpath
[16:57:14] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:57:16] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:625) [intermediary-Sodium%201.16.4.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:409) [intermediary-Sodium%201.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [intermediary-Sodium%201.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
[16:57:16] [main/INFO]: Setting user: ferreiraevil
[16:57:17] [main/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:57:17] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[16:57:20] [Worker-Bootstrap-3/INFO]: Finished building data fixers after 10387ms
[16:57:24] [main/INFO]: Narrator library for x64 successfully loaded
[16:57:24] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Loader, Fabric Structure API (v1), Fabric Containers (v0), Lithium, Fabric Object Builder API (v1), ASH - Another Simple HUD, Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Sodium, Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), No Fog, Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Phosphor, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Item API (v1), Fabric Entity Events (v1), Fabric Rendering (v0), Cull Leaves, Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v4, Fabric Resource Loader (v0), Auto Config v1 Updated, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Registry Sync (v0), Fabric Commands (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[16:57:42] [main/INFO]: OpenAL initialized.
[16:57:42] [main/INFO]: Sound engine started
[16:57:42] [main/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[16:57:42] [main/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[16:57:45] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[16:57:45] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[16:57:45] [main/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[16:57:45] [main/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[16:57:45] [main/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:57:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[16:57:49] [main/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:57:50] [main/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:57:53] [main/INFO]: Stopping!

**Comment by VileSmith** [comment]
Do you know what it can be?

**Comment by LucilleTea** [comment]
Your log doesn't have anything of note, except the fact that authentication failed.
I was using my Cadmium with the recent release of Hydrogen without issue, although when I updated to magneticflux's MethodHandles PR I did finally encounter #1. I think #1 often won't show up in the latest.log, though you should see it in the launcher's log window or maybe the crash report - so I suspect you are seeing this.

That issue is not a specific mod incompatibility, it seems to be Cadmium simply failing to launch when too much else is loaded - maybe a race condition? Either way I don't have a solution for that currently. If you are encountering that problem, I'd recommend using LazyDFU instead of Cadmium.

**Comment by VileSmith** [comment]
Ok, thank you so much i will try. I'm a Brazilian fan of yours and of jellysquid3

**Comment by LucilleTea** [comment]
Actually, it doesn't look like the other issue I mentioned either - since we have this line
`[16:57:20] [Worker-Bootstrap-3/INFO]: Finished building data fixers after 10387ms`
As far as this log says, hydrogen and cadmium started up successfully. There's no further information in the log to say what the actual issue is, so I can't really suggest anything.
